model:
  target: models.viton.Lit_viton
  params:
    lr: 1e-4
    sampling_step: 5
    num_sampling: 20
    optim_name: Adam
    model_args:
      stage: "stage_1"
      GC_config:
        target: diffusers.models.unet_2d.UNet2DModel
        params:
          in_channels: 4
          out_channels: 4
          down_block_types:
          - DownBlock2D
          - DownBlock2D
          - DownBlock2D
          - DownBlock2D
          up_block_types:
          - UpBlock2D
          - UpBlock2D
          - UpBlock2D
          - UpBlock2D
          block_out_channels:
          - 256
          - 512
          - 1024
          - 1024
      GC_config:
        target: 
        params:

logger:
  logger_path: checkpoints
    
lightning:
  trainer:
    strategy: ddp_find_unused_parameters_True
    precision: 16-mixed
    max_epochs: 100000
    sync_batchnorm: True
    devices: [0]
  earlystop_params:
    monitor: val/loss
    mode: min
  monitor_params:
    logging_interval: step

dataset:
  height: 256
  width: 192
  num_workers: 6
  batch_size: 16
  train:
    target: dataloader.viton.VitonDataset
    params:
      dataroot_path: data/VITON
      phase: train
      outputlist:
      - c_name
      - im_name
      - image
      - cloth
      - inpaint_mask
      - pose_map
      - im_head
      - im_pose
      - im_cloth
  val:
    target: dataloader.viton.VitonDataset
    params:
      dataroot_path: data/VITON
      phase: val
      outputlist:
      - c_name
      - im_name
      - image
      - cloth
      - inpaint_mask
      - pose_map
      - im_head
      - im_pose
      - im_cloth
  test:
    target: dataloader.viton.VitonDataset
    params:
      dataroot_path: data/VITON
      phase: test
      order: paired
      outputlist:
      - c_name
      - im_name
      - image
      - cloth
      - inpaint_mask
      - pose_map
      - im_head
      - im_pose
      - im_cloth
