model:
  target: models.cnn.CNN.LitCNN
  params:
    optim_name: Adam
    lr: 1e-3
    model_name: AlexNet
    model_args:
      image_channel: 1
      image_size: 227
      out_features: 10
  
data:
  image_mean: 0.5
  image_std: 0.5