model:
  target: models.cnn.CNN.LitCNN
  params:
    optim_name: Adam
    lr: 1e-3
    model_name: ResNet
    model_args:
      image_channel: 1
      image_size: 224
      out_features: 10
      res_layers: 152 #18, 34, 50, 101, 152
  
data:
  data_name: MNIST
  image_mean: 0.5
  image_std: 0.5