model:
  target: models.cnn.CNN.LitCNN
  params:
    optim_name: Adam
    lr: 1e-3
    model_name: VGGNet
    model_args:
      in_channels: 1
      out_features: 10
      vgg_layers: 11 #,13, 16, 19
  
data:
  image_mean: 0.5
  image_std: 0.5
  image_channel: 1
  image_size: 224