model:
  target: models.gan.GAN.Lit_gan
  params:
    optim_name: Adam
    lr: 0.0002
    model_name: VanilaGAN
    model_args:
      latent_dim: 100
      image_channel: 1
      image_size: 28
  
data:
  data_name: MNIST
  image_mean: 0.5
  image_std: 0.5