model:
  target: models.gan.GAN.LitGAN
  params:
    optim_name: RMSprop
    lr: 0.00005
    model_name: WGAN
    model_args:
      latent_dim: 100
      image_channel: 1
      image_size: 64
data:
  image_mean: 0.5
  image_std: 0.5