model:
  target: models.ae.AE.Lit_ae
  params:
    optim_name: Adam
    lr: 0.005
    model_name: MLPAE
    model_args:
      image_channel: 1
      image_size: 28
data:
  data_name: MNIST
  image_mean: 0.5
  image_std: 0.5