model:
  target: models.ae.AE.LitAE
  params:
    optim_name: Adam
    lr: 0.0002
    model_name: Unet
    model_args:
      image_channel: 1
      image_size: 32
data:
  data_name: MNIST
  image_mean: 0.5
  image_std: 0.5