model:
  target: models.base.Lit_base
  params:
    lr: 1.e-6
    sampling_step: 5
    num_sampling: 20
    model_config:
      target: models.vton.master_thesis
      params:
        optim_target: torch.optim.adamw.AdamW
        dataset_name: dresscode
        in_channels: 31
        num_inference_steps: 50
        cloth_warpping: False
        cloth_refinement: True
        img2img: False
        model_path: checkpoints/vton/master_thesis/DressCode/unet.ckpt
        criterion_config:
          target: torch.nn.MSELoss
        scheduler_config:
          target: diffusers.schedulers.scheduling_ddim.DDIMScheduler
          params:
            num_train_timesteps: 1000

logger:
  logger_path: checkpoints/vton/master_thesis/DressCode/
    
lightning:
  trainer:
    strategy: ddp_find_unused_parameters_True
    # precision: 16-mixed
    max_epochs: 100000
    sync_batchnorm: True
    devices: [0]
  earlystop_params:
    monitor: val/total_loss
    mode: min
  monitor_params:
    logging_interval: step

dataset:
  height: &height 512
  width: &width 384
  num_workers: 6
  batch_size: 2
  train:
    target: &data_target dataloader.dresscode.DressCodeDataset
    params:
      size: [*height, *width]
      dataroot_path: &dataroot_path data/DressCode
      phase: train
      category: &data_category
      - upper_body
      - lower_body
      - dresses
      outputlist: &data_outputlist
      - im_name
      - image
      - cloth
      - im_mask
      - inpaint_mask
      - pose_map
      - captions
      - category
      - warped_cloth
  val:
    target: *data_target
    params:
      size: [*height, *width]
      dataroot_path: *dataroot_path
      phase: val
      category: *data_category
      outputlist: *data_outputlist
  test:
    target: *data_target
    params:
      size: [*height, *width]
      phase: test
      order: paired
      dataroot_path: *dataroot_path
      category: *data_category
      outputlist: *data_outputlist