model:
  target: models.base.Lit_base
  params:
    lr: 0.00000001
    sampling_step: 5
    num_sampling: 20
    model_config:
      target: models.vton.stable_diffusion_text_guided_inpainting_vton
      params:
        optim_target: torch.optim.adamw.AdamW
        criterion_config:
          target: torch.nn.MSELoss
        num_inference_steps: 50
        use_caption: Ture
        model_path: checkpoints/vton/stable_diffusion_text_guided_inpainting_vton/DressCode/unet.ckpt
        train_resume: True

logger:
  logger_path: checkpoints/vton/stable_diffusion_text_guided_inpainting_vton/DressCode/tryon
    
lightning:
  use_earlystop: True
  use_monitor: True
  earlystop_params:
    monitor: val/total_loss
    mode: min
  monitor_params:
    logging_interval: step
  trainer:
    strategy: ddp_find_unused_parameters_True
    # precision: 16-mixed
    max_epochs: 100000
    sync_batchnorm: True
    # devices: [0]

dataset:
  height: &height 512
  width: &width 384
  num_workers: 6
  batch_size: 16
  train:
    target: &data_target dataloader.dresscode.DressCodeDataset
    params:
      size: [*height, *width]
      dataroot_path: &dataroot_path data/DressCode
      phase: train
      category: &data_category
      - upper_body
      - lower_body
      - dresses
      outputlist: &data_outputlist
      - c_name
      - im_name
      - image
      - inpaint_mask
      - im_mask
      - category
      - captions
  val:
    target: *data_target
    params:
      size: [*height, *width]
      dataroot_path: *dataroot_path
      phase: val
      category: *data_category
      outputlist: *data_outputlist
  test:
    target: *data_target
    params:
      size: [*height, *width]
      phase: test
      order: paired
      dataroot_path: *dataroot_path
      category: *data_category
      outputlist: *data_outputlist