model:
  target: models.diffusion.Diffusers.LitDiffusers
  params:
    lr: 1e-4
    img2img: True
    sampling_step: 50
    optim_name: Adam
    model_name: UnconditionalLDM
    model_args:
      sample_size: [256, 192]
      in_channels: 4
      out_channels: 4
      num_train_steps: 1000
      num_inference_steps: 50
      num_sampling: 3
      eta: 0.0