model:
  target: models.base.Lit_base
  params:
    lr: 1.e-6
    sampling_step: 5
    num_sampling: 20
    model_config:
      target: models.diffusion.frido
      params:
        optim_target: torch.optim.adamw.AdamW
        num_inference_steps: 50
        cloth_warpping: False
        cloth_refinement: False
        img2img: False
        model_path: checkpoints/diffusion/frido/msvqgan/DressCode/frido_f16f8.ckpt
        criterion_config:
          target: torch.nn.MSELoss
        scheduler_config:
          target: diffusers.schedulers.scheduling_ddim.DDIMScheduler
          params:
            num_train_timesteps: 1000
        vae_config:
          target: models.vae.msvqgan
          params:
            optim_target: torch.optim.adam.Adam
            model_path: checkpoints/diffusion/frido/msvqgan/DressCode/msvqgan_f16f8.ckpt
            embed_dim: [4, 4]
            n_embed: [8192, 8192]
            encoder_config:
              target: models.Diffusion.Frido.taming.modules.diffusionmodules.model.MSEncoder
              params:
                multiscale: 2
                double_z: False
                z_channels: [4, 4]
                resolution: 256
                in_channels: 3
                out_ch: 3
                ch: 128
                ch_mult: [ 1,1,2,2,4 ]  # num_down = len(ch_mult)-1
                num_res_blocks: 2
                attn_resolutions: [32]
                dropout: 0.0
            decoder_config:
              target: models.Diffusion.Frido.taming.modules.diffusionmodules.model.Decoder
              params:
                double_z: False
                z_channels: 8
                resolution: 256
                in_channels: 3
                out_ch: 3
                ch: 128
                ch_mult: [ 1,1,2,4 ]  # num_down = len(ch_mult)-1
                num_res_blocks: 2
                attn_resolutions: [32]
                dropout: 0.0
            criterion_config:
              target: models.Diffusion.Frido.taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
              params:
                disc_conditional: False
                disc_in_channels: 3
                disc_num_layers: 2
                disc_start: 30001
                disc_weight: 0.8
                codebook_weight: 1.0
        unet_config:
          target: models.Diffusion.Frido.frido.modules.diffusionmodules.pyunet.PyUNetModel
          params:
            image_size: 32
            use_split_head: true
            split_embed_dim_list: [4, 4]
            use_SPADE_norm: true
            in_channels: 8
            out_channels: 8
            model_channels: 192
            attention_resolutions:
            - 8
            - 4
            - 2
            num_res_blocks: 2
            channel_mult:
            - 1
            - 2
            - 3
            - 5
            num_head_channels: 32
            use_spatial_transformer: true
            transformer_depth: 1
            context_dim: 640
            num_stage: 2

logger:
  logger_path: checkpoints/diffusion/frido/msvqgan/DressCode
    
lightning:
  trainer:
    strategy: ddp_find_unused_parameters_True
    # precision: 16-mixed
    max_epochs: 100000
    sync_batchnorm: True
    devices: [0]
  earlystop_params:
    monitor: val/total_loss
    mode: min
  monitor_params:
    logging_interval: step

dataset:
  height: &height 512
  width: &width 384
  num_workers: 6
  batch_size: 2
  train:
    target: &data_target dataloader.dresscode.DressCodeDataset
    params:
      size: [*height, *width]
      dataroot_path: &dataroot_path data/DressCode
      phase: train
      category: &data_category
      - upper_body
      - lower_body
      - dresses
      outputlist: &data_outputlist
      - im_name
      - image
      - captions
  val:
    target: *data_target
    params:
      size: [*height, *width]
      dataroot_path: *dataroot_path
      phase: val
      category: *data_category
      outputlist: *data_outputlist
  test:
    target: *data_target
    params:
      size: [*height, *width]
      phase: test
      order: paired
      dataroot_path: *dataroot_path
      category: *data_category
      outputlist: *data_outputlist