model:
  target: models.vae.Lit_msvqgan
  params:
    lr: 4.5e-6
    sampling_step: 5
    num_sampling: 20
    model_config:
      target: models.vae.msvqgan
      params:
        optim_target: torch.optim.adam.Adam
        model_path: checkpoints/diffusion/frido/msvqgan/DressCode/msvqgan_f16f8.ckpt
        embed_dim: [3, 3]
        n_embed: [4096, 4096]
        encoder_config:
          target: models.Diffusion.Frido.taming.modules.diffusionmodules.model.MSEncoder
          params:
            multiscale: 2
            double_z: False
            z_channels: [3, 3]
            resolution: 256
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult: [ 1,1,2,4 ]  # num_down = len(ch_mult)-1
            num_res_blocks: 2
            attn_resolutions: [64]
            dropout: 0.0
        decoder_config:
          target: models.Diffusion.Frido.taming.modules.diffusionmodules.model.Decoder
          params:
            double_z: False
            z_channels: 6
            resolution: 256
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
            num_res_blocks: 2
            attn_resolutions: [64]
            dropout: 0.0
        criterion_config:
          target: models.Diffusion.Frido.taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
          params:
            disc_conditional: False
            disc_in_channels: 3
            disc_start: 0
            disc_weight: 0.75
            codebook_weight: 1.0

logger:
  logger_path: checkpoints/diffusion/frido/msvqgan/DressCode
    
lightning:
  trainer:
    strategy: ddp_find_unused_parameters_False
    # precision: 16-mixed
    max_epochs: 100000
    sync_batchnorm: True
    devices: [0]
  earlystop_params:
    # monitor: val/total_ae_loss
    # mode: min
  monitor_params:
    # logging_interval: step

dataset:
  height: &height 256
  width: &width 192
  num_workers: 6
  batch_size: 2
  train:
    target: &data_target dataloader.dresscode.DressCodeDataset
    params:
      size: [*height, *width]
      dataroot_path: &dataroot_path data/DressCode
      phase: train
      category: &data_category
      - upper_body
      - lower_body
      - dresses
      outputlist: &data_outputlist
      - c_name
      - im_name
      - image
      - cloth
      - inpaint_mask
      - pose_map
      - im_head
      - im_pose
      - im_cloth
      - category
      - im_mask
  val:
    target: *data_target
    params:
      size: [*height, *width]
      dataroot_path: *dataroot_path
      phase: val
      category: *data_category
      outputlist: *data_outputlist
  test:
    target: *data_target
    params:
      size: [*height, *width]
      phase: test
      order: paired
      dataroot_path: *dataroot_path
      category: *data_category
      outputlist: *data_outputlist