model:
  target: models.vae.Lit_vae
  params:
    lr: 4.5e-6
    sampling_step: 5
    num_sampling: 20
    optim_name: AdamW
    model_name: msvqgan
    model_args:
      model_path: checkpoints/diffusion/frido/msvqgan
      encoder_config:
        target: models.Diffusion.Frido.taming.modules.diffusionmodules.model.MSEncoder
        params:
          multiscale: 2
          double_z: False
          z_channels: [4, 4]
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,1,2,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [32]
          dropout: 0.0
      decoder_config:
        target: models.Diffusion.Frido.taming.modules.diffusionmodules.model.Decoder
        params:
          double_z: False
          z_channels: 8
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [32]
          dropout: 0.0
      loss_config:
      target: models.Diffusion.Frido.taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_num_layers: 2
        disc_start: 30001
        disc_weight: 0.8
        codebook_weight: 1.0

logger:
  logger_path: checkpoints/diffusion/frido/DressCode/tryon
    
lightning:
  trainer:
    strategy: ddp_find_unused_parameters_False
    # precision: 16-mixed
    max_epochs: 100000
    sync_batchnorm: True
    devices: [0]
  earlystop_params:
    monitor: val/total_loss
    mode: min
  monitor_params:
    logging_interval: step

dataset:
  height: &height 512
  width: &width 384
  num_workers: 6
  batch_size: 8
  train:
    target: &data_target dataloader.dresscode.DressCodeDataset
    params:
      size: [*height, *width]
      dataroot_path: &dataroot_path data/DressCode
      phase: train
      category: &data_category
      - upper_body
      - lower_body
      - dresses
      outputlist: &data_outputlist
      - c_name
      - im_name
      - image
      - cloth
      - inpaint_mask
      - pose_map
      - im_head
      - im_pose
      - im_cloth
      - category
      - im_mask
  val:
    target: *data_target
    params:
      size: [*height, *width]
      dataroot_path: *dataroot_path
      phase: val
      category: *data_category
      outputlist: *data_outputlist
  test:
    target: *data_target
    params:
      size: [*height, *width]
      phase: test
      order: paired
      dataroot_path: *dataroot_path
      category: *data_category
      outputlist: *data_outputlist